In [1]:
%matplotlib inline
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
file_landmarks = "Resources/AllLandmarks.csv"
file_murals = "Resources/Mural_Registry.csv"

landmarks_df = pd.read_csv(file_landmarks)
murals_df = pd.read_csv(file_murals)

In [3]:
landmarks_df

,LANDMARK NAME,ID,ADDRESS,DATE BUILT,ARCHITECT,LANDMARK DESIGNATION DATE,LATITUDE,LONGITUDE,LOCATION,ZIP CODE,Type
0,Vassar Swiss Underwear Company Building,L-265,2543 - 2545 W Diversey Av,NaN,NaN,7/30/2008,41.931627,-87.692100,"(41.9316266084, -87.6921000957)",60647,Landmark
1,Mathilde Eliel House,L- 89,4122 S Ellis Av,1886,Adler & Sullivan,10/2/1991,41.819256,-87.602788,"(41.819255751, -87.6027879992)",60653,Landmark
2,Manhattan Building,L-139,431 S Dearborn St,1891,William LeBaron Jenney,7/7/1978,41.876066,-87.628964,"(41.8760657234, -87.6289644505)",60605,Landmark
3,Machinery Hall at Illinois Institute of Techno...,L- 12,"100 W 33rd St, Chicago, IL",1901,"Patton, Fisher & Miller",5/26/2004,41.835161,-87.629221,"(41.8351614122, -87.6292212235)",60616,Landmark
4,Melissa Ann Elam House,L- 88,4726 S Dr Martin Luther King Jr Dr,1903,Henry L. Newhouse,3/21/1979,41.808530,-87.617204,"(41.808529769, -87.6172043949)",60615,Landmark
...,...,...,...,...,...,...,...,...,...,...,...
312,(Former) Schlitz BreweryTied-House@1944 N.Oakley,L-310,1944 N. Oakley Ave.,1898,Kley & Lang,10/5/2011,41.917484,-87.685256,"(41.917484239, -87.6852556957)",60647,Landmark
313,Getty Tomb,L-103,"Graceland Cemetery, 4011 N Clark St",1890,Louis H. Sullivan,3/10/1971,41.961230,-87.661189,"(41.9612300749, -87.6611886208)",60613,Landmark
314,"Engine Company 129, Truck 50",L-236,8120 S Ashland Av,1928-29,Argyle E. Robinson,10/1/2003,41.746005,-87.663706,"(41.746005133, -87.6637057717)",60620,Landmark
315,James Charnley House,L- 65,1365 N Astor st,1891,"Adler and Sullivan, Frank Lloyd Wright",8/20/1972,41.907648,-87.627478,"(41.9076480171, -87.627477823)",60610,Landmark
316,Beeson House and Coach House,L-224,5810 W Midway Park,1892,Frederick Schock,1/20/1999,41.889318,-87.770608,"(41.8893178892, -87.7706081072)",60644,Landmark

In [4]:
landmarks_df.columns= landmarks_df.columns.str.lower()
landmarks_df

,landmark name,id,address,date built,architect,landmark designation date,latitude,longitude,location,zip code,type
0,Vassar Swiss Underwear Company Building,L-265,2543 - 2545 W Diversey Av,NaN,NaN,7/30/2008,41.931627,-87.692100,"(41.9316266084, -87.6921000957)",60647,Landmark
1,Mathilde Eliel House,L- 89,4122 S Ellis Av,1886,Adler & Sullivan,10/2/1991,41.819256,-87.602788,"(41.819255751, -87.6027879992)",60653,Landmark
2,Manhattan Building,L-139,431 S Dearborn St,1891,William LeBaron Jenney,7/7/1978,41.876066,-87.628964,"(41.8760657234, -87.6289644505)",60605,Landmark
3,Machinery Hall at Illinois Institute of Techno...,L- 12,"100 W 33rd St, Chicago, IL",1901,"Patton, Fisher & Miller",5/26/2004,41.835161,-87.629221,"(41.8351614122, -87.6292212235)",60616,Landmark
4,Melissa Ann Elam House,L- 88,4726 S Dr Martin Luther King Jr Dr,1903,Henry L. Newhouse,3/21/1979,41.808530,-87.617204,"(41.808529769, -87.6172043949)",60615,Landmark
...,...,...,...,...,...,...,...,...,...,...,...
312,(Former) Schlitz BreweryTied-House@1944 N.Oakley,L-310,1944 N. Oakley Ave.,1898,Kley & Lang,10/5/2011,41.917484,-87.685256,"(41.917484239, -87.6852556957)",60647,Landmark
313,Getty Tomb,L-103,"Graceland Cemetery, 4011 N Clark St",1890,Louis H. Sullivan,3/10/1971,41.961230,-87.661189,"(41.9612300749, -87.6611886208)",60613,Landmark
314,"Engine Company 129, Truck 50",L-236,8120 S Ashland Av,1928-29,Argyle E. Robinson,10/1/2003,41.746005,-87.663706,"(41.746005133, -87.6637057717)",60620,Landmark
315,James Charnley House,L- 65,1365 N Astor st,1891,"Adler and Sullivan, Frank Lloyd Wright",8/20/1972,41.907648,-87.627478,"(41.9076480171, -87.627477823)",60610,Landmark
316,Beeson House and Coach House,L-224,5810 W Midway Park,1892,Frederick Schock,1/20/1999,41.889318,-87.770608,"(41.8893178892, -87.7706081072)",60644,Landmark

In [5]:
landmarks_df = landmarks_df.rename(columns={'landmark name': 'name', 'architect': 'artist', 'date built': 'year installed'})
landmarks_df

,name,id,address,year installed,artist,landmark designation date,latitude,longitude,location,zip code,type
0,Vassar Swiss Underwear Company Building,L-265,2543 - 2545 W Diversey Av,NaN,NaN,7/30/2008,41.931627,-87.692100,"(41.9316266084, -87.6921000957)",60647,Landmark
1,Mathilde Eliel House,L- 89,4122 S Ellis Av,1886,Adler & Sullivan,10/2/1991,41.819256,-87.602788,"(41.819255751, -87.6027879992)",60653,Landmark
2,Manhattan Building,L-139,431 S Dearborn St,1891,William LeBaron Jenney,7/7/1978,41.876066,-87.628964,"(41.8760657234, -87.6289644505)",60605,Landmark
3,Machinery Hall at Illinois Institute of Techno...,L- 12,"100 W 33rd St, Chicago, IL",1901,"Patton, Fisher & Miller",5/26/2004,41.835161,-87.629221,"(41.8351614122, -87.6292212235)",60616,Landmark
4,Melissa Ann Elam House,L- 88,4726 S Dr Martin Luther King Jr Dr,1903,Henry L. Newhouse,3/21/1979,41.808530,-87.617204,"(41.808529769, -87.6172043949)",60615,Landmark
...,...,...,...,...,...,...,...,...,...,...,...
312,(Former) Schlitz BreweryTied-House@1944 N.Oakley,L-310,1944 N. Oakley Ave.,1898,Kley & Lang,10/5/2011,41.917484,-87.685256,"(41.917484239, -87.6852556957)",60647,Landmark
313,Getty Tomb,L-103,"Graceland Cemetery, 4011 N Clark St",1890,Louis H. Sullivan,3/10/1971,41.961230,-87.661189,"(41.9612300749, -87.6611886208)",60613,Landmark
314,"Engine Company 129, Truck 50",L-236,8120 S Ashland Av,1928-29,Argyle E. Robinson,10/1/2003,41.746005,-87.663706,"(41.746005133, -87.6637057717)",60620,Landmark
315,James Charnley House,L- 65,1365 N Astor st,1891,"Adler and Sullivan, Frank Lloyd Wright",8/20/1972,41.907648,-87.627478,"(41.9076480171, -87.627477823)",60610,Landmark
316,Beeson House and Coach House,L-224,5810 W Midway Park,1892,Frederick Schock,1/20/1999,41.889318,-87.770608,"(41.8893178892, -87.7706081072)",60644,Landmark

In [6]:
landmarks_df.columns

Index(['name', 'id', 'address', 'year installed', 'artist',
       'landmark designation date', 'latitude', 'longitude', 'location',
       'zip code', 'type'],
      dtype='object')

In [7]:
landmarks_df = landmarks_df[['name', 'address', 'year installed', 'artist',
       'landmark designation date', 'latitude', 'longitude','zip code', 'type']]
landmarks_df

,name,address,year installed,artist,landmark designation date,latitude,longitude,zip code,type
0,Vassar Swiss Underwear Company Building,2543 - 2545 W Diversey Av,NaN,NaN,7/30/2008,41.931627,-87.692100,60647,Landmark
1,Mathilde Eliel House,4122 S Ellis Av,1886,Adler & Sullivan,10/2/1991,41.819256,-87.602788,60653,Landmark
2,Manhattan Building,431 S Dearborn St,1891,William LeBaron Jenney,7/7/1978,41.876066,-87.628964,60605,Landmark
3,Machinery Hall at Illinois Institute of Techno...,"100 W 33rd St, Chicago, IL",1901,"Patton, Fisher & Miller",5/26/2004,41.835161,-87.629221,60616,Landmark
4,Melissa Ann Elam House,4726 S Dr Martin Luther King Jr Dr,1903,Henry L. Newhouse,3/21/1979,41.808530,-87.617204,60615,Landmark
...,...,...,...,...,...,...,...,...,...
312,(Former) Schlitz BreweryTied-House@1944 N.Oakley,1944 N. Oakley Ave.,1898,Kley & Lang,10/5/2011,41.917484,-87.685256,60647,Landmark
313,Getty Tomb,"Graceland Cemetery, 4011 N Clark St",1890,Louis H. Sullivan,3/10/1971,41.961230,-87.661189,60613,Landmark
314,"Engine Company 129, Truck 50",8120 S Ashland Av,1928-29,Argyle E. Robinson,10/1/2003,41.746005,-87.663706,60620,Landmark
315,James Charnley House,1365 N Astor st,1891,"Adler and Sullivan, Frank Lloyd Wright",8/20/1972,41.907648,-87.627478,60610,Landmark
316,Beeson House and Coach House,5810 W Midway Park,1892,Frederick Schock,1/20/1999,41.889318,-87.770608,60644,Landmark

In [8]:
landmarks_df = landmarks_df[landmarks_df['latitude'].notna()]
landmarks_df = landmarks_df[landmarks_df['longitude'].notna()]
landmarks_df

,name,address,year installed,artist,landmark designation date,latitude,longitude,zip code,type
0,Vassar Swiss Underwear Company Building,2543 - 2545 W Diversey Av,NaN,NaN,7/30/2008,41.931627,-87.692100,60647,Landmark
1,Mathilde Eliel House,4122 S Ellis Av,1886,Adler & Sullivan,10/2/1991,41.819256,-87.602788,60653,Landmark
2,Manhattan Building,431 S Dearborn St,1891,William LeBaron Jenney,7/7/1978,41.876066,-87.628964,60605,Landmark
3,Machinery Hall at Illinois Institute of Techno...,"100 W 33rd St, Chicago, IL",1901,"Patton, Fisher & Miller",5/26/2004,41.835161,-87.629221,60616,Landmark
4,Melissa Ann Elam House,4726 S Dr Martin Luther King Jr Dr,1903,Henry L. Newhouse,3/21/1979,41.808530,-87.617204,60615,Landmark
...,...,...,...,...,...,...,...,...,...
312,(Former) Schlitz BreweryTied-House@1944 N.Oakley,1944 N. Oakley Ave.,1898,Kley & Lang,10/5/2011,41.917484,-87.685256,60647,Landmark
313,Getty Tomb,"Graceland Cemetery, 4011 N Clark St",1890,Louis H. Sullivan,3/10/1971,41.961230,-87.661189,60613,Landmark
314,"Engine Company 129, Truck 50",8120 S Ashland Av,1928-29,Argyle E. Robinson,10/1/2003,41.746005,-87.663706,60620,Landmark
315,James Charnley House,1365 N Astor st,1891,"Adler and Sullivan, Frank Lloyd Wright",8/20/1972,41.907648,-87.627478,60610,Landmark
316,Beeson House and Coach House,5810 W Midway Park,1892,Frederick Schock,1/20/1999,41.889318,-87.770608,60644,Landmark

In [9]:
murals_df

,Mural Registration ID,Artist Credit,Artwork Title,Media,Year Installed,Year Restored,Location Description,Street Address,Zip,Ward,Community Area Number,Affiliated (or Commissioning) Organization,Description of Artwork,Latitude,Longitude,Location,Type
0,19006,John Pitman Weber,TILT (Together Protect the Community),NaN,1976.0,2005.0,NaN,2100 West Division St,60622.0,2.0,25,Chicago Public Art Group,NaN,41.903255,-87.67982505,POINT (-87.67982505 41.90325452),Mural
1,19043,"Rahmaan Statik, Max Sansing",Sepia,Paint,2016.0,NaN,NaN,2230 S. Central Park Ave,60623.0,22.0,NaN,Chicago Public Art Group,NaN,41.850922,-87.715009,POINT (-87.715009 41.850922),Mural
2,19064,Damon Reed & Moses Ball,Change Makers,NaN,2006.0,NaN,NaN,3819 Ogden Ave,60623.0,22.0,NaN,Chicago Public Art Group,Artists: Damon Reed & Moses Ball2005,NaN,NaN,NaN,Mural
3,19154,Shawnimals,NaN,Paint,2018.0,NaN,Cards Against Humanity HQ,1551 W Homer Street,60642.0,2.0,22,Cards Against Humanity HQ,"Shawn Smith, creator of Shawnimals and Ninjato...",41.917209,-87.66683738,POINT (-87.66683738 41.91720864),Mural
4,19161,Cara Feeney,Community Mural,Paint,2016.0,NaN,Red Line CTA Viaduct on Ardmore,1124-1160 W Ardmore Ave,60660.0,48.0,NaN,NaN,City of Chicago granted us rights to use the w...,41.987298,-87.658921,POINT (-87.658921 41.987298),Mural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,19310,Justus Roe,16th & Ashland,Acrylic and exterior latex paint,2013.0,2019.0,Embankment wall 1600-1540 w. 16th st at north ...,1600 w. 16th st,60608.0,25.0,28,NaN,abstract landscape painting,41.859717,-87.66623522,POINT (-87.66623522 41.85971662),Mural
352,19216,Uneek and Flash,Block by Block,spray,2012.0,NaN,North facing wall of Athletico,4080 N Milwaukee,60641.0,45.0,15,NaN,"""Block By Block"" was painted as the first sanc...",41.955021,-87.74979329,POINT (-87.74979329000001 41.95502071),Mural
353,19223,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",mosaic/tile,2013.0,NaN,Bike Trail Underpass,4300 W. Peterson Avenue,60646.0,39.0,12,Sauganash Mural Project,NaN,41.990149,-87.73627807,POINT (-87.73627807 41.99014944),Mural
354,19233,Matthew Hoffman,You Are Beautiful,NaN,2016.0,NaN,NaN,1039 W Lawrence Ave,60640.0,46.0,3,NaN,NaN,41.968959,-87.65636687,POINT (-87.65636687 41.96895857),Mural
355,19101,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,Paint and Mixed Media,2017.0,NaN,459 W. Division street,459 West Division St,60610.0,27.0,37,Chicago Public Art Group,NaN,41.903649,-87.64046322,POINT (-87.64046322 41.90364882),Mural

In [10]:
murals_df = murals_df.rename(columns={'Mural Registration ID': 'ID','Artist Credit': 'Artist', 'Zip': 'Zip Code', 'Street Address': 'Address', 'Artwork Title': 'Name'})
murals_df

,ID,Artist,Name,Media,Year Installed,Year Restored,Location Description,Address,Zip Code,Ward,Community Area Number,Affiliated (or Commissioning) Organization,Description of Artwork,Latitude,Longitude,Location,Type
0,19006,John Pitman Weber,TILT (Together Protect the Community),NaN,1976.0,2005.0,NaN,2100 West Division St,60622.0,2.0,25,Chicago Public Art Group,NaN,41.903255,-87.67982505,POINT (-87.67982505 41.90325452),Mural
1,19043,"Rahmaan Statik, Max Sansing",Sepia,Paint,2016.0,NaN,NaN,2230 S. Central Park Ave,60623.0,22.0,NaN,Chicago Public Art Group,NaN,41.850922,-87.715009,POINT (-87.715009 41.850922),Mural
2,19064,Damon Reed & Moses Ball,Change Makers,NaN,2006.0,NaN,NaN,3819 Ogden Ave,60623.0,22.0,NaN,Chicago Public Art Group,Artists: Damon Reed & Moses Ball2005,NaN,NaN,NaN,Mural
3,19154,Shawnimals,NaN,Paint,2018.0,NaN,Cards Against Humanity HQ,1551 W Homer Street,60642.0,2.0,22,Cards Against Humanity HQ,"Shawn Smith, creator of Shawnimals and Ninjato...",41.917209,-87.66683738,POINT (-87.66683738 41.91720864),Mural
4,19161,Cara Feeney,Community Mural,Paint,2016.0,NaN,Red Line CTA Viaduct on Ardmore,1124-1160 W Ardmore Ave,60660.0,48.0,NaN,NaN,City of Chicago granted us rights to use the w...,41.987298,-87.658921,POINT (-87.658921 41.987298),Mural
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351,19310,Justus Roe,16th & Ashland,Acrylic and exterior latex paint,2013.0,2019.0,Embankment wall 1600-1540 w. 16th st at north ...,1600 w. 16th st,60608.0,25.0,28,NaN,abstract landscape painting,41.859717,-87.66623522,POINT (-87.66623522 41.85971662),Mural
352,19216,Uneek and Flash,Block by Block,spray,2012.0,NaN,North facing wall of Athletico,4080 N Milwaukee,60641.0,45.0,15,NaN,"""Block By Block"" was painted as the first sanc...",41.955021,-87.74979329,POINT (-87.74979329000001 41.95502071),Mural
353,19223,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",mosaic/tile,2013.0,NaN,Bike Trail Underpass,4300 W. Peterson Avenue,60646.0,39.0,12,Sauganash Mural Project,NaN,41.990149,-87.73627807,POINT (-87.73627807 41.99014944),Mural
354,19233,Matthew Hoffman,You Are Beautiful,NaN,2016.0,NaN,NaN,1039 W Lawrence Ave,60640.0,46.0,3,NaN,NaN,41.968959,-87.65636687,POINT (-87.65636687 41.96895857),Mural
355,19101,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,Paint and Mixed Media,2017.0,NaN,459 W. Division street,459 West Division St,60610.0,27.0,37,Chicago Public Art Group,NaN,41.903649,-87.64046322,POINT (-87.64046322 41.90364882),Mural

In [11]:
murals_df.columns

Index(['ID', 'Artist', 'Name', 'Media', 'Year Installed', 'Year Restored',
       'Location Description', 'Address', 'Zip Code', 'Ward',
       'Community Area Number', 'Affiliated (or Commissioning) Organization',
       'Description of Artwork', 'Latitude', 'Longitude', 'Location', 'Type'],
      dtype='object')

In [12]:
murals_df = murals_df[['Artist', 'Name',
       'Year Installed', 'Address', 'Zip Code', 'Description of Artwork',
       'Latitude', 'Longitude', 'Type']]
murals_df

,Artist,Name,Year Installed,Address,Zip Code,Description of Artwork,Latitude,Longitude,Type
0,John Pitman Weber,TILT (Together Protect the Community),1976.0,2100 West Division St,60622.0,NaN,41.903255,-87.67982505,Mural
1,"Rahmaan Statik, Max Sansing",Sepia,2016.0,2230 S. Central Park Ave,60623.0,NaN,41.850922,-87.715009,Mural
2,Damon Reed & Moses Ball,Change Makers,2006.0,3819 Ogden Ave,60623.0,Artists: Damon Reed & Moses Ball2005,NaN,NaN,Mural
3,Shawnimals,NaN,2018.0,1551 W Homer Street,60642.0,"Shawn Smith, creator of Shawnimals and Ninjato...",41.917209,-87.66683738,Mural
4,Cara Feeney,Community Mural,2016.0,1124-1160 W Ardmore Ave,60660.0,City of Chicago granted us rights to use the w...,41.987298,-87.658921,Mural
...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608.0,abstract landscape painting,41.859717,-87.66623522,Mural
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641.0,"""Block By Block"" was painted as the first sanc...",41.955021,-87.74979329,Mural
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646.0,NaN,41.990149,-87.73627807,Mural
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640.0,NaN,41.968959,-87.65636687,Mural
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610.0,NaN,41.903649,-87.64046322,Mural

In [13]:
murals_df = murals_df[murals_df['Latitude'].notna()]
murals_df = murals_df[murals_df['Longitude'].notna()]
murals_df = murals_df[murals_df['Zip Code'].notna()]
murals_df

,Artist,Name,Year Installed,Address,Zip Code,Description of Artwork,Latitude,Longitude,Type
0,John Pitman Weber,TILT (Together Protect the Community),1976.0,2100 West Division St,60622.0,NaN,41.903255,-87.67982505,Mural
1,"Rahmaan Statik, Max Sansing",Sepia,2016.0,2230 S. Central Park Ave,60623.0,NaN,41.850922,-87.715009,Mural
3,Shawnimals,NaN,2018.0,1551 W Homer Street,60642.0,"Shawn Smith, creator of Shawnimals and Ninjato...",41.917209,-87.66683738,Mural
4,Cara Feeney,Community Mural,2016.0,1124-1160 W Ardmore Ave,60660.0,City of Chicago granted us rights to use the w...,41.987298,-87.658921,Mural
5,ASVP,Make Your Own Luck,2015.0,1 E Balbo,60605.0,NaN,41.872983,-87.62752137,Mural
...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608.0,abstract landscape painting,41.859717,-87.66623522,Mural
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641.0,"""Block By Block"" was painted as the first sanc...",41.955021,-87.74979329,Mural
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646.0,NaN,41.990149,-87.73627807,Mural
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640.0,NaN,41.968959,-87.65636687,Mural
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610.0,NaN,41.903649,-87.64046322,Mural

In [14]:
murals_df.columns= murals_df.columns.str.lower()
murals_df

,artist,name,year installed,address,zip code,description of artwork,latitude,longitude,type
0,John Pitman Weber,TILT (Together Protect the Community),1976.0,2100 West Division St,60622.0,NaN,41.903255,-87.67982505,Mural
1,"Rahmaan Statik, Max Sansing",Sepia,2016.0,2230 S. Central Park Ave,60623.0,NaN,41.850922,-87.715009,Mural
3,Shawnimals,NaN,2018.0,1551 W Homer Street,60642.0,"Shawn Smith, creator of Shawnimals and Ninjato...",41.917209,-87.66683738,Mural
4,Cara Feeney,Community Mural,2016.0,1124-1160 W Ardmore Ave,60660.0,City of Chicago granted us rights to use the w...,41.987298,-87.658921,Mural
5,ASVP,Make Your Own Luck,2015.0,1 E Balbo,60605.0,NaN,41.872983,-87.62752137,Mural
...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608.0,abstract landscape painting,41.859717,-87.66623522,Mural
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641.0,"""Block By Block"" was painted as the first sanc...",41.955021,-87.74979329,Mural
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646.0,NaN,41.990149,-87.73627807,Mural
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640.0,NaN,41.968959,-87.65636687,Mural
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610.0,NaN,41.903649,-87.64046322,Mural

In [15]:
murals_df['longitude'] = pd.to_numeric(murals_df['longitude'], errors='coerce')
landmarks_df['year installed'] = pd.to_numeric(landmarks_df['year installed'], errors='coerce')

In [16]:
murals_df.dtypes

artist                     object
name                       object
year installed            float64
address                    object
zip code                  float64
description of artwork     object
latitude                  float64
longitude                 float64
type                       object
dtype: object

In [17]:
landmarks_df.dtypes

name                          object
address                       object
year installed               float64
artist                        object
landmark designation date     object
latitude                     float64
longitude                    float64
zip code                      object
type                          object
dtype: object

In [18]:
landmarks_df = landmarks_df[['artist', 'name', 'year installed', 'address', 'zip code', 'latitude', 'longitude', 'type', 'landmark designation date']]
landmarks_df.dtypes

artist                        object
name                          object
year installed               float64
address                       object
zip code                      object
latitude                     float64
longitude                    float64
type                          object
landmark designation date     object
dtype: object

In [19]:
murals_df = murals_df[['artist', 'name', 'year installed', 'address', 'zip code', 'latitude', 'longitude', 'type', 'description of artwork']]
murals_df.dtypes

artist                     object
name                       object
year installed            float64
address                    object
zip code                  float64
latitude                  float64
longitude                 float64
type                       object
description of artwork     object
dtype: object

In [20]:
chicago_df = landmarks_df.append(murals_df)
chicago_df

,artist,name,year installed,address,zip code,latitude,longitude,type,landmark designation date,description of artwork
0,NaN,Vassar Swiss Underwear Company Building,NaN,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886.0,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891.0,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901.0,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903.0,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610,41.903649,-87.640463,Mural,NaN,NaN

In [21]:
chicago_df.columns = chicago_df.columns.str.replace(' ', '_')
chicago_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,NaN,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886.0,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891.0,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901.0,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903.0,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610,41.903649,-87.640463,Mural,NaN,NaN

In [22]:
chicago_df['year_installed'].fillna(0, inplace=True)
chicago_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,0.0,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886.0,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891.0,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901.0,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903.0,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013.0,1600 w. 16th st,60608,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012.0,4080 N Milwaukee,60641,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013.0,4300 W. Peterson Avenue,60646,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016.0,1039 W Lawrence Ave,60640,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017.0,459 West Division St,60610,41.903649,-87.640463,Mural,NaN,NaN

In [29]:
chicago_df['year_installed'] = chicago_df['year_installed'].astype(int)
chicago_df['zip_code'] = chicago_df['zip_code'].astype(str)

chicago_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,0,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013,1600 w. 16th st,60608.0,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012,4080 N Milwaukee,60641.0,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013,4300 W. Peterson Avenue,60646.0,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016,1039 W Lawrence Ave,60640.0,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017,459 West Division St,60610.0,41.903649,-87.640463,Mural,NaN,NaN

In [30]:
chicago_df.columns

Index(['artist', 'name', 'year_installed', 'address', 'zip_code', 'latitude',
       'longitude', 'type', 'landmark_designation_date',
       'description_of_artwork'],
      dtype='object')

In [31]:
chicago_df.dtypes

artist                        object
name                          object
year_installed                 int32
address                       object
zip_code                      object
latitude                     float64
longitude                    float64
type                          object
landmark_designation_date     object
description_of_artwork        object
dtype: object

In [32]:
chicago_df = chicago_df[chicago_df['zip_code'].notna()]

In [33]:
chicago_df.to_csv("Resources/chicago_df.csv")
chicago_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,0,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013,1600 w. 16th st,60608.0,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012,4080 N Milwaukee,60641.0,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013,4300 W. Peterson Avenue,60646.0,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016,1039 W Lawrence Ave,60640.0,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017,459 West Division St,60610.0,41.903649,-87.640463,Mural,NaN,NaN

In [34]:
chicago2_df=chicago_df.drop([102, 113, 115, 152])
chicago2_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,0,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013,1600 w. 16th st,60608.0,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012,4080 N Milwaukee,60641.0,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013,4300 W. Peterson Avenue,60646.0,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016,1039 W Lawrence Ave,60640.0,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017,459 West Division St,60610.0,41.903649,-87.640463,Mural,NaN,NaN

In [42]:
chicago2_df.to_csv("Resources/chicago2_df.csv")
chicago2_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,NaN,Vassar Swiss Underwear Company Building,0,2543 - 2545 W Diversey Av,60647,41.931627,-87.692100,Landmark,7/30/2008,NaN
1,Adler & Sullivan,Mathilde Eliel House,1886,4122 S Ellis Av,60653,41.819256,-87.602788,Landmark,10/2/1991,NaN
2,William LeBaron Jenney,Manhattan Building,1891,431 S Dearborn St,60605,41.876066,-87.628964,Landmark,7/7/1978,NaN
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.629221,Landmark,5/26/2004,NaN
4,Henry L. Newhouse,Melissa Ann Elam House,1903,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.617204,Landmark,3/21/1979,NaN
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013,1600 w. 16th st,60608.0,41.859717,-87.666235,Mural,NaN,abstract landscape painting
352,Uneek and Flash,Block by Block,2012,4080 N Milwaukee,60641.0,41.955021,-87.749793,Mural,NaN,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013,4300 W. Peterson Avenue,60646.0,41.990149,-87.736278,Mural,NaN,NaN
354,Matthew Hoffman,You Are Beautiful,2016,1039 W Lawrence Ave,60640.0,41.968959,-87.656367,Mural,NaN,NaN
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017,459 West Division St,60610.0,41.903649,-87.640463,Mural,NaN,NaN

In [37]:
chicago3_df = chicago2_df.replace(np.nan, 'Unknown', regex=True)
chicago3_df

,artist,name,year_installed,address,zip_code,latitude,longitude,type,landmark_designation_date,description_of_artwork
0,Unknown,Vassar Swiss Underwear Company Building,0,2543 - 2545 W Diversey Av,60647,41.931627,-87.6921,Landmark,7/30/2008,Unknown
1,Adler & Sullivan,Mathilde Eliel House,1886,4122 S Ellis Av,60653,41.819256,-87.6028,Landmark,10/2/1991,Unknown
2,William LeBaron Jenney,Manhattan Building,1891,431 S Dearborn St,60605,41.876066,-87.629,Landmark,7/7/1978,Unknown
3,"Patton, Fisher & Miller",Machinery Hall at Illinois Institute of Techno...,1901,"100 W 33rd St, Chicago, IL",60616,41.835161,-87.6292,Landmark,5/26/2004,Unknown
4,Henry L. Newhouse,Melissa Ann Elam House,1903,4726 S Dr Martin Luther King Jr Dr,60615,41.808530,-87.6172,Landmark,3/21/1979,Unknown
...,...,...,...,...,...,...,...,...,...,...
351,Justus Roe,16th & Ashland,2013,1600 w. 16th st,60608.0,41.859717,-87.6662,Mural,Unknown,abstract landscape painting
352,Uneek and Flash,Block by Block,2012,4080 N Milwaukee,60641.0,41.955021,-87.7498,Mural,Unknown,"""Block By Block"" was painted as the first sanc..."
353,Todd Osborne and Tracy VanDuinen,"Sauganash Mural Project, North Wall",2013,4300 W. Peterson Avenue,60646.0,41.990149,-87.7363,Mural,Unknown,Unknown
354,Matthew Hoffman,You Are Beautiful,2016,1039 W Lawrence Ave,60640.0,41.968959,-87.6564,Mural,Unknown,Unknown
355,"Mirtes Zwierzynski, Ruben Aguirre",Parkside of Old Town,2017,459 West Division St,60610.0,41.903649,-87.6405,Mural,Unknown,Unknown

In [40]:
chicago3_df.to_csv("Resources/chicago3_df.csv")

In [49]:
engine = create_engine('postgresql://postgres:password@localhost:5432/chicago3_df', paramstyle='format')

In [50]:
chicago3_df.to_sql(name='chicago', con=engine, if_exists='append', index=False)

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)

In [48]:
pd.read_sql_query('select * from chicago LIMIT 20', con=engine).head()

OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/e3q8)